package net.harawata.mapper;

import java.util.List;
import net.harawata.domain.Person;
import net.harawata.domain.PersonExample;
import org.apache.ibatis.annotations.Param;

public interface PersonMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table person
     * 
     * @mbggenerated
     */
    int countByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table person
     * 
     * @mbggenerated
     */
    int deleteByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table person
     * 
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table person
     * 
     * @mbggenerated
     */
    int insert(Person record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table person
     * 
     * @mbggenerated
     */
    int insertSelective(Person record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table person
     * 
     * @mbggenerated
     */
    List<Person> selectByExample(PersonExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table person
     * 
     * @mbggenerated
     */
    Person selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table person
     * 
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Person record,
            @Param("example") PersonExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table person
     * 
     * @mbggenerated
     */
    int updateByExample(@Param("record") Person record,
            @Param("example") PersonExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table person
     * 
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Person record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table person
     * 
     * @mbggenerated
     */
    int updateByPrimaryKey(Person record);

    Person selectPersonAndPetsByPrimaryKey(Integer id);

    List<Person> selectPersonAndPetsByExample(PersonExample example);
}