package net.harawata.mapper;

import java.util.List;
import net.harawata.domain.Pet;
import net.harawata.domain.PetExample;
import org.apache.ibatis.annotations.Param;

public interface PetMapper {

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table pet
     * 
     * @mbggenerated
     */
    int countByExample(PetExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table pet
     * 
     * @mbggenerated
     */
    int deleteByExample(PetExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table pet
     * 
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer petId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table pet
     * 
     * @mbggenerated
     */
    int insert(Pet record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table pet
     * 
     * @mbggenerated
     */
    int insertSelective(Pet record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table pet
     * 
     * @mbggenerated
     */
    List<Pet> selectByExample(PetExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table pet
     * 
     * @mbggenerated
     */
    Pet selectByPrimaryKey(Integer petId);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table pet
     * 
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Pet record,
            @Param("example") PetExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table pet
     * 
     * @mbggenerated
     */
    int updateByExample(@Param("record") Pet record,
            @Param("example") PetExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table pet
     * 
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Pet record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds
     * to the database table pet
     * 
     * @mbggenerated
     */
    int updateByPrimaryKey(Pet record);
}