package net.harawata.domain;

import java.util.List;

public class Person {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column person.id
     * 
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column person.name
     * 
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column person.gender
     * 
     * @mbggenerated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column person.email
     * 
     * @mbggenerated
     */
    private String email;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column person.id
     * 
     * @return the value of person.id
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column person.id
     * 
     * @param id
     *            the value for person.id
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column person.name
     * 
     * @return the value of person.name
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column person.name
     * 
     * @param name
     *            the value for person.name
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column person.gender
     * 
     * @return the value of person.gender
     * @mbggenerated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column person.gender
     * 
     * @param gender
     *            the value for person.gender
     * @mbggenerated
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column person.email
     * 
     * @return the value of person.email
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column person.email
     * 
     * @param email
     *            the value for person.email
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    private List<Pet> pets;

    public List<Pet> getPets() {
        return pets;
    }

    public void setPets(List<Pet> pets) {
        this.pets = pets;
    }
}