package net.harawata.domain;

public class Pet {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column pet.pet_id
     * 
     * @mbggenerated
     */
    private Integer petId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column pet.owner_id
     * 
     * @mbggenerated
     */
    private Integer ownerId;

    /**
     * This field was generated by MyBatis Generator. This field corresponds to
     * the database column pet.pet_name
     * 
     * @mbggenerated
     */
    private String petName;

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column pet.pet_id
     * 
     * @return the value of pet.pet_id
     * @mbggenerated
     */
    public Integer getPetId() {
        return petId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column pet.pet_id
     * 
     * @param petId
     *            the value for pet.pet_id
     * @mbggenerated
     */
    public void setPetId(Integer petId) {
        this.petId = petId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column pet.owner_id
     * 
     * @return the value of pet.owner_id
     * @mbggenerated
     */
    public Integer getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column pet.owner_id
     * 
     * @param ownerId
     *            the value for pet.owner_id
     * @mbggenerated
     */
    public void setOwnerId(Integer ownerId) {
        this.ownerId = ownerId;
    }

    /**
     * This method was generated by MyBatis Generator. This method returns the
     * value of the database column pet.pet_name
     * 
     * @return the value of pet.pet_name
     * @mbggenerated
     */
    public String getPetName() {
        return petName;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the
     * value of the database column pet.pet_name
     * 
     * @param petName
     *            the value for pet.pet_name
     * @mbggenerated
     */
    public void setPetName(String petName) {
        this.petName = petName;
    }
}